#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

BUILD_DATE=$(date +%Y%m%d)

# Tars up the required system files and dirctories.
tar cvzf ./centos-6-${BUILD_DATE}.tar.gz --exclude-from=exclude.txt /data/chroot/
