#!/usr/bin/env bash
#
# Build a chroot with a CentOS 6.6 base install.
#

CHROOT=/data/chroot

if [ -d $CHROOT ]; then
  echo "Found previous chroot. Deleting and creating a new one."
  rm -rf $CHROOT
  mkdir -p $CHROOT
  mkdir -p $CHROOT/var/lib/rpm
fi

rpm --rebuilddb --root=$CHROOT

MIRROR=http://mirror.centos.org/centos/6/os/x86_64/Packages
PACKAGE=centos-release-6-6.el6.centos.12.2.x86_64.rpm

wget -O /var/tmp/$PACKAGE $MIRROR/$PACKAGE

rpm -i --root=$CHROOT --nodeps /var/tmp/$PACKAGE

yum --installroot=$CHROOT install -y @core

echo "Removing /var/tmp/$PACKAGE"
rm -rf /var/tmp/$PACKAGE
