#!/usr/bin/env bash
#
# Copyright (c) 2015 Joyent Inc., All rights reserved.
#
# Install CentOS 6.6 into a directory, modify the installation, then tar it up.
#

set -euo pipefail
IFS=$'\n\t'

INSTALL_DIR=/data/chroot
MIRROR=http://yum.tamu.edu/centos/6/os/x86_64/Packages
PACKAGE=centos-release-6-6.el6.centos.12.2.x86_64.rpm
NAME="CentOS 6.6 LX Brand"
BUILD_DATE=$(date +%Y%m%d)
DOCS="https://docs.joyent.com/images/lx-brand-beta"
TARGET="centos-6-lx-${BUILD_DATE}.tar.gz"

echo "==> Installing CentOS 6.6 into $INSTALL_DIR"

if [ -d $INSTALL_DIR ]; then
  echo "====> Found previous chroot. Deleting and creating a new one."
  rm -rf $INSTALL_DIR
  mkdir -p $INSTALL_DIR
  mkdir -p $INSTALL_DIR/var/lib/rpm
fi

rpm --rebuilddb --root=$INSTALL_DIR

echo "==> Getting CentOS 6.6 rpm..."
wget -O /var/tmp/$PACKAGE $MIRROR/$PACKAGE

echo "==> Veryfying CentOS 6.6 rpm..."
rpm -K /var/tmp/$PACKAGE

echo "==> Installing rpm package..."
rpm -i --root=$INSTALL_DIR --nodeps /var/tmp/$PACKAGE

echo "==> Installing @core packages..."
yum --installroot=$INSTALL_DIR install -y @core

echo "==> Installing additional packages..."
yum --installroot=$INSTALL_DIR install -y vim-common vim-enhanced wget man man-pages

echo "==> Removing all '*-firmware' packages (inlcuding the kernel-firmware)"
yum --installroot=$INSTALL_DIR erase -y "*-firmware"

echo "==> Cleaning up yum cache..."
yum --installroot=$INSTALL_DIR clean all

echo "==> Removing /var/tmp/$PACKAGE"
rm -rf /var/tmp/$PACKAGE

echo "==> Setting TZ to UTC"
rm $INSTALL_DIR/etc/localtime
cp $INSTALL_DIR/usr/share/zoneinfo/UTC $INSTALL_DIR/etc/localtime

echo "==> Disabling PasswordAuthentication"
sed s/PasswordAuthentication\ yes/PasswordAuthentication\ no/ -i $INSTALL_DIR/etc/ssh/sshd_config

echo "==> Creating /etc/motd"
cat << MOTD > $INSTALL_DIR/etc/motd
   __        .                   .
 _|  |_      | .-. .  . .-. :--. |-
|_    _|     ;|   ||  |(.-' |  | |
  |__|   \`--'  \`-' \`;-| \`-' '  ' \`-'
                   /  ;  Instance ($NAME $BUILD_DATE)
                   \`-'   $DOCS

MOTD

echo "==> Creating /etc/product file"
cat << PRODUCT > $INSTALL_DIR/etc/product
Name: Joyent Instance
Image: $NAME $BUILD_DATE
Documentation: $DOCS
Description: $NAME $BUILD_DATE.
PRODUCT

echo "==> Installing Guest tools in $INSTALL_DIR"
chroot $INSTALL_DIR ln -s /native/usr/sbin/mdata-get /usr/sbin/mdata-get
chroot $INSTALL_DIR ln -s /native/usr/sbin/mdata-put /usr/sbin/mdata-put
chroot $INSTALL_DIR ln -s /native/usr/sbin/mdata-delete /usr/sbin/mdata-delete
chroot $INSTALL_DIR ln -s /native/usr/sbin/mdata-list /usr/sbin/mdata-list
cp -r ./guest-tools/usr/share/man/man1/mdata-* $INSTALL_DIR/usr/share/man/man1/
cp ./guest-tools/lib/smartdc/joyent_rc.local $INSTALL_DIR/etc/rc.d/rc.local
echo "==> Done!"
sleep 1 

echo "==> Saving installation as $TARGET. This may take a few minutes."
tar czf $TARGET --exclude-from=exclude.txt $INSTALL_DIR/

echo "==> Installation complete!"
echo "==> $TARGET"

exit 0
