#!/usr/bin/env bash
#
# Copyright (c) 2015 Joyent Inc., All rights reserved.
#
# Install CentOS 6.6 into a directory, modify the installation, then tar it up.
#

set -euo pipefail
IFS=$'\n\t'

PACKAGE=centos-release-6-6.el6.centos.12.2.x86_64.rpm
GUESTTOOLS=guesttools
BUILD_DATE=$(date +%Y%m%d)

usage() {
cat <<EOF

  Usage: $0 -d <chroot> -m <mirror> -i <image name> -p <proper name> -u <image docs>
  
  Install and modify CentOS in a given directory in a given directory using a given mirror

  Example:
  $0 -d /data/chroot -m http://mirror.centos.org/centos/6/os/x86_64/Packages -i lx-centos-6 -p "CentOS 6.6 LX Brand" -u https://docs.joyent.com/images/lx-brand-beta

  OPTIONS:
  -d A path to the install directory
  -m A URL for the desired archive mirror
  -i The name of the image. This is used for naming the tarball. 
  -p The proper name of the image. Use quotes. This is used in the MOTD and /etc/product file. 
  -u A URL to the image docs [optional]
  -h Show this message

EOF
}

INSTALL_DIR=
MIRROR=
IMAGE_NAME=
NAME=
DOCS=

while getopts "hd:m:i:p:u:" OPTION
do
  case $OPTION in
    h)
      usage
      exit
      ;;
    d)
      INSTALL_DIR=${OPTARG%/}
      ;;
    m)
      MIRROR=${OPTARG%/}
      ;;
    i)
      IMAGE_NAME=${OPTARG}
      ;;
    p)
      NAME=${OPTARG}
      ;;
    u)
      DOCS=${OPTARG}
      ;;
    \?)
      usage
      exit
      ;;
  esac
done

if [[ $# -eq 0 ]]; then
  usage
  exit 1
fi

if [[ ! -e ${INSTALL_DIR} ]] ; then
  echo "Directory $INSTALL_DIR not found"
  exit 1
fi

if [[ -z ${INSTALL_DIR} ]]; then
  echo "Error: missing install directory (-d) value"
  exit 1
fi

if [[ -z ${MIRROR} ]]; then
  echo "Error: missing mirror (-m) value"
  exit 1
fi

if [[ -z ${IMAGE_NAME} ]]; then
  echo "Error: missing image name (-i) value"
  exit 1
fi

if [[ -z ${NAME} ]]; then
  echo "Error: missing proper name (-p) value"
  exit 1
fi

TARGET="${IMAGE_NAME}-${BUILD_DATE}.tar.gz"

if [[ -z ${DOCS} ]]; then
  DOCS="https://docs.joyent.com/images/lx-brand-beta"
fi

echo "==> Installing CentOS 6.6 into $INSTALL_DIR"

if [[ -d $INSTALL_DIR ]]; then
  echo "====> Found previous chroot. Deleting and creating a new one."
  rm -rf $INSTALL_DIR
  mkdir -p $INSTALL_DIR
  mkdir -p $INSTALL_DIR/var/lib/rpm
fi

rpm --rebuilddb --root=$INSTALL_DIR

echo "==> Getting CentOS 6.6 rpm..."
wget -O /var/tmp/$PACKAGE $MIRROR/$PACKAGE

echo "==> Veryfying CentOS 6.6 rpm..."
rpm -K /var/tmp/$PACKAGE

echo "==> Installing rpm package..."
rpm -i --root=$INSTALL_DIR --nodeps /var/tmp/$PACKAGE

echo "==> Installing @core packages..."
yum --installroot=$INSTALL_DIR install -y @core

echo "==> Installing additional packages..."
yum --installroot=$INSTALL_DIR install -y vim-common vim-enhanced wget man man-pages

echo "==> Removing all '*-firmware' packages (inlcuding the kernel-firmware)"
yum --installroot=$INSTALL_DIR erase -y "*-firmware"

echo "==> Cleaning up yum cache..."
yum --installroot=$INSTALL_DIR clean all

echo "==> Removing /var/tmp/$PACKAGE"
rm -rf /var/tmp/$PACKAGE

echo "==> Setting TZ to UTC"
rm $INSTALL_DIR/etc/localtime
cp $INSTALL_DIR/usr/share/zoneinfo/UTC $INSTALL_DIR/etc/localtime

echo "==> Disabling PasswordAuthentication"
sed s/PasswordAuthentication\ yes/PasswordAuthentication\ no/ -i $INSTALL_DIR/etc/ssh/sshd_config

echo "==> Creating /etc/motd"
cat << MOTD > $INSTALL_DIR/etc/motd
   __        .                   .
 _|  |_      | .-. .  . .-. :--. |-
|_    _|     ;|   ||  |(.-' |  | |
  |__|   \`--'  \`-' \`;-| \`-' '  ' \`-'
                   /  ;  Instance ($NAME $BUILD_DATE)
                   \`-'   $DOCS

MOTD

echo "==> Creating /etc/product file"
cat << PRODUCT > $INSTALL_DIR/etc/product
Name: Joyent Instance
Image: $NAME $BUILD_DATE
Documentation: $DOCS
Description: $NAME $BUILD_DATE.
PRODUCT

echo "==> Installing Guest tools in $INSTALL_DIR"
echo "====> Initiallizing and fetching submodule $GUESTTOOLS"
git submodule init
git submodule update
echo "====> Running ./install.sh -i $INSTALL_DIR"
cd $GUESTTOOLS
./install.sh -i $INSTALL_DIR
cd ..

echo "==> Saving installation as $TARGET. This may take a few minutes."
tar czf $TARGET --exclude-from=exclude.txt $INSTALL_DIR/

echo "==> Installation complete!"
echo "==> $TARGET"

exit 0
