#!/bin/sh

LD_LIBRARY_PATH_32="/native/lib:/native/usr/lib"
LD_PRELOAD=/native/usr/lib/brand/lx/lx_thunk.so.1
LD_BIND_NOW=1
export LD_LIBRARY_PATH LD_PRELOAD LD_BIND_NOW

exec /native/usr/lib/brand/lx/lx_native /native/usr/lib/ld.so.1 /native/usr/sbin/mdata-delete $@
